language: java
dist: precise
jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11
- openjdk12
script:
- ./gradlew -i check
after_success:
- ./gradlew test jacocoTestReport coveralls
notifications:
  email: false
  slack:
    secure: HRTTJBAN+Xi077lfQBAe1LMuNi5AoXlRWLp6z608T+CYsvJ0afxWzVQdX4CV2ZgQk5c+n2XzKgPaN55vZFZkPv56WXAJs04+jjgH10pdCtc9k9hoXVUIi+0a2iAAYySD2o035aMlATkodNVmBmPeCApuvZCUVQsvYmbs9AJC0JzJzu8ZyufeTQymSDAHdm+KG14gyvplw1rfsxV2JA4hOcqQ9B6w1P3oVyMT557j8HqkYy032PjsQtz6E3ujT0itQ1Y06Gz2jlvkCnrQabQ7Sfj2sAFNn7Ri8aFFoabUKVlNzyRZbHDLLwrapDS0O6M92QaaCYq7/bQvW0Etn67yQ45Z8MTQsptmnHFIQyNTDItYpvfLBORlnynZMj5oz2Fw3GIwX1LKVQgVi0P+EKo84CjkSliROfIb/sBFd1NwMXIHzTK+sY1LXVaouRTnq9JzY3tDTwbmF64DSpEMP+gPbXKWxb/FRsfj603rv3lxggs70L403F1BliKJzHOHX+sN1VQEdKgEpDxqU4nXtLrF+kVLpFIDJ0T1fMYAHA9Xr4ovP2JYjxxS7rgi2a5bofi4qDYyRBB/8yfzus8uReTSXOLTAHwmw30frjmukB51hbBH2brzNleyCHjOhzEnNZDZgssTFAdPyaqChMgBwh8SvA/DPvZgc3ycOiL+06jJJRw=
